### ISSUE TITLE
Upload sample audio files

### ISSUE THREAD

**Issue by hemajv** [redhat-et/whisper-self-hosted-llm#4]
Upload sample audio files that can be used and include a French audio file for presenting at Kubecon

**Comment by hemajv** [comment]
uploaded a few audio samples: https://github.com/redhat-et/whisper-self-hosted-llm/tree/main/data

**Comment by aakankshaduggal** [comment]
Added two french audio samples - https://github.com/redhat-et/whisper-self-hosted-llm/tree/main/data
